// <auto-generated />
using System;
using HRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMS.Infrastructure.Migrations.EmployeeDB
{
    [DbContext(typeof(EmployeeDBContext))]
    [Migration("20221014170552_update_audiable")]
    partial class update_audiable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("HRMS.Entities.BasicInfo", b =>
                {
                    b.Property<string>("BasicInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdharName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dependents")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GaurdianType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuardianName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaritalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nominee")
                        .HasColumnType("TEXT");

                    b.Property<string>("PAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModified")
                        .HasColumnType("TEXT");

                    b.HasKey("BasicInfoId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("BasicInfos");
                });

            modelBuilder.Entity("HRMS.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModified")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRMS.Entities.BasicInfo", b =>
                {
                    b.HasOne("HRMS.Entities.Employee", "Employee")
                        .WithOne("EmployeeBasicInfo")
                        .HasForeignKey("HRMS.Entities.BasicInfo", "EmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
